name: Automated testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  l3build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # GitHub Actions do not regenerate the test if the key does not change, so
      # we integrate a random UUID into the key to keep them different.
      # DO NOT CHANGE THIS
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid

      # Actually load the cache.  Since we never reuse the key, we need
      # restore-keys to indicate the prefix of our cahces.  This loads the
      # newest cache with this prefix in the key.
      #
      # If we want to force regeneration of the cache, increase the number after
      # *both* instances of "texlive-v"
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive-v1-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v1-

      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          # List the required TeX Live packages in a separate file to allow
          # reuse in different workflows.
          package_file: .github/tl_packages
        continue-on-error: true

      - name: Run l3build
        run: l3build ctan -q -H
