name: l3build
on: [ push, pull_request ]

jobs:
  l3build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dante-ev/latex-action@latest
        with:
          entrypoint: l3build ctan -q -H
